# nixpacks.toml
providers = ["node"]

[variables]
# hier die gewünschte Node-Major angeben
NIXPACKS_NODE_VERSION = "23"   # (oder "23", wenn deine Nixpacks-Version das schon kann)

[phases.install]
cmds = [
  # nvm installieren
  "export NVM_DIR=\"$HOME/.nvm\" && mkdir -p \"$NVM_DIR\" && curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash",

  # nvm laden und Node 23 aktivieren (alles in EINEM Step)
  "export NVM_DIR=\"$HOME/.nvm\" && . \"$NVM_DIR/nvm.sh\" && nvm install 23 && nvm use 23 && node -v && npm -v",
  
  "export NVM_DIR=\"$HOME/.nvm\" && . \"$NVM_DIR/nvm.sh\" && npm ci"
]

[phases.build]
cmds = [
  # zur Sicherheit erneut nvm sourcen (neuer Step!)
  "export NVM_DIR=\"$HOME/.nvm\" && . \"$NVM_DIR/nvm.sh\" && node -v",

  # Build/Generate laufen lassen (Nuxt, Next, etc.)
  "export NVM_DIR=\"$HOME/.nvm\" && . \"$NVM_DIR/nvm.sh\" && pnpm run generate"
]