# nixpacks.toml
providers = ["node"]

[variables]
# hier die gewünschte Node-Major angeben
NIXPACKS_NODE_VERSION = "23"   # (oder "23", wenn deine Nixpacks-Version das schon kann)

[phases.install]
# Corepack + pnpm sicherstellen und Dependencies installieren
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@9 --activate",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]  # oder "pnpm run generate" je nach Projekt