// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *General Settings → Social Media Links*
 */
export interface GeneralSettingsDocumentDataSocialMediaLinksItem {
  /**
   * Name field in *General Settings → Social Media Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.social_media_links[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * URL field in *General Settings → Social Media Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.social_media_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *General Settings → Menu*
 */
export interface GeneralSettingsDocumentDataMenuItem {
  /**
   * Parent Link field in *General Settings → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.menu[].parent_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  parent_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Sub Items field in *General Settings → Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.menu[].sub_items
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sub_items: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for General Settings documents
 */
interface GeneralSettingsDocumentData {
  /**
   * Logo field in *General Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Company field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Address field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Contact Name field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.contact_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_name: prismic.KeyTextField;

  /**
   * Contact Email field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact Telephone field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.contact_telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_telephone: prismic.KeyTextField;

  /**
   * Social Media Links field in *General Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.social_media_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media_links: prismic.GroupField<
    Simplify<GeneralSettingsDocumentDataSocialMediaLinksItem>
  >;

  /**
   * Legal Menu field in *General Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.legal_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  legal_menu: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Copyright field in *General Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField /**
   * CTA Button field in *General Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.cta_button
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */;
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Menu Image field in *General Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.menu_image
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  menu_image: prismic.ImageField<never>;

  /**
   * Menu field in *General Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: general_settings.menu[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu: prismic.GroupField<Simplify<GeneralSettingsDocumentDataMenuItem>>;
}

/**
 * General Settings document from Prismic
 *
 * - **API ID**: `general_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GeneralSettingsDocumentData>,
    "general_settings",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TitleTextListSlice
  | TeamSlice
  | SplitPageHeroSlice
  | LargeTextSlice
  | MediaWithTextSlice
  | QuotesSlice
  | ImageCardsSlice
  | FullMediaSlice
  | AnimatedNumbersSlice
  | GallerySlice
  | SeperatorSlice
  | ParallaxSlice
  | LogosSlice
  | StartHeroSlice
  | AccordionGroupSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never> /**
   * Transparent Header field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.transparent_header
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */;
  transparent_header: prismic.BooleanField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = GeneralSettingsDocument | PageDocument;

/**
 * Item in *AccordionGroup → Default → Primary → Items*
 */
export interface AccordionGroupSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *AccordionGroup → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_group.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *AccordionGroup → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_group.default.primary.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *AccordionGroup → Default → Primary*
 */
export interface AccordionGroupSliceDefaultPrimary {
  /**
   * Title field in *AccordionGroup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_group.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *AccordionGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_group.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<AccordionGroupSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for AccordionGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionGroupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AccordionGroup*
 */
type AccordionGroupSliceVariation = AccordionGroupSliceDefault;

/**
 * AccordionGroup Shared Slice
 *
 * - **API ID**: `accordion_group`
 * - **Description**: AccordionGroup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionGroupSlice = prismic.SharedSlice<
  "accordion_group",
  AccordionGroupSliceVariation
>;

/**
 * Item in *AnimatedNumbers → Default → Primary → Numbers*
 */
export interface AnimatedNumbersSliceDefaultPrimaryNumbersItem {
  /**
   * Number field in *AnimatedNumbers → Default → Primary → Numbers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.numbers[].number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * Unit field in *AnimatedNumbers → Default → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.numbers[].unit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  unit: prismic.KeyTextField;

  /**
   * Title field in *AnimatedNumbers → Default → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.numbers[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *AnimatedNumbers → Animated Numbers - Split Row → Primary → Numbers*
 */
export interface AnimatedNumbersSliceAnimatedNumbersSplitRowPrimaryNumbersItem {
  /**
   * Number field in *AnimatedNumbers → Animated Numbers - Split Row → Primary → Numbers*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.numbers[].number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * Unit field in *AnimatedNumbers → Animated Numbers - Split Row → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.numbers[].unit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  unit: prismic.KeyTextField;

  /**
   * Title field in *AnimatedNumbers → Animated Numbers - Split Row → Primary → Numbers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.numbers[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *AnimatedNumbers → Default → Primary*
 */
export interface AnimatedNumbersSliceDefaultPrimary {
  /**
   * Numbers field in *AnimatedNumbers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.numbers[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  numbers: prismic.GroupField<
    Simplify<AnimatedNumbersSliceDefaultPrimaryNumbersItem>
  >;

  /**
   * Content Color field in *AnimatedNumbers → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.content_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  content_color: prismic.ColorField;

  /**
   * Background Color field in *AnimatedNumbers → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for AnimatedNumbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnimatedNumbersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnimatedNumbersSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AnimatedNumbers → Animated Numbers - Split Row → Primary*
 */
export interface AnimatedNumbersSliceAnimatedNumbersSplitRowPrimary {
  /**
   * Numbers field in *AnimatedNumbers → Animated Numbers - Split Row → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.numbers[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  numbers: prismic.GroupField<
    Simplify<AnimatedNumbersSliceAnimatedNumbersSplitRowPrimaryNumbersItem>
  >;

  /**
   * Title field in *AnimatedNumbers → Animated Numbers - Split Row → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AnimatedNumbers → Animated Numbers - Split Row → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *AnimatedNumbers → Animated Numbers - Split Row → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_numbers.animatedNumbersSplitRow.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Animated Numbers - Split Row variation for AnimatedNumbers Slice
 *
 * - **API ID**: `animatedNumbersSplitRow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnimatedNumbersSliceAnimatedNumbersSplitRow =
  prismic.SharedSliceVariation<
    "animatedNumbersSplitRow",
    Simplify<AnimatedNumbersSliceAnimatedNumbersSplitRowPrimary>,
    never
  >;

/**
 * Slice variation for *AnimatedNumbers*
 */
type AnimatedNumbersSliceVariation =
  | AnimatedNumbersSliceDefault
  | AnimatedNumbersSliceAnimatedNumbersSplitRow;

/**
 * AnimatedNumbers Shared Slice
 *
 * - **API ID**: `animated_numbers`
 * - **Description**: AnimatedNumbers
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnimatedNumbersSlice = prismic.SharedSlice<
  "animated_numbers",
  AnimatedNumbersSliceVariation
>;

/**
 * Primary content in *FullMedia → Default → Primary*
 */
export interface FullMediaSliceDefaultPrimary {
  /**
   * Media field in *FullMedia → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: full_media.default.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for FullMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullMediaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullMedia*
 */
type FullMediaSliceVariation = FullMediaSliceDefault;

/**
 * FullMedia Shared Slice
 *
 * - **API ID**: `full_media`
 * - **Description**: FullMedia
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullMediaSlice = prismic.SharedSlice<
  "full_media",
  FullMediaSliceVariation
>;

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Overline field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * Media field in *Gallery → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Item in *ImageCards → Default → Primary → Items*
 */
export interface ImageCardsSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *ImageCards → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageCards → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Button field in *ImageCards → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.items[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Items field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Primary content in *LargeText → Default → Primary*
 */
export interface LargeTextSliceDefaultPrimary {
  /**
   * Title field in *LargeText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Side Text field in *LargeText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_text.default.primary.side_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  side_text: prismic.KeyTextField;

  /**
   * Description field in *LargeText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *LargeText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: large_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Vertical Spacing field in *LargeText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal
   * - **API ID Path**: large_text.default.primary.vertical_spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_spacing: prismic.SelectField<"normal" | "large" | "small", "filled">;
}

/**
 * Default variation for LargeText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LargeText*
 */
type LargeTextSliceVariation = LargeTextSliceDefault;

/**
 * LargeText Shared Slice
 *
 * - **API ID**: `large_text`
 * - **Description**: LargeText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeTextSlice = prismic.SharedSlice<
  "large_text",
  LargeTextSliceVariation
>;

/**
 * Primary content in *Logos → Items*
 */
export interface LogosSliceDefaultItem {
  /**
   * Logo field in *Logos → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].logo
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  logo: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Company field in *Logos → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<LogosSliceDefaultItem>
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogosSlice = prismic.SharedSlice<"logos", LogosSliceVariation>;

/**
 * Primary content in *MediaWithText → Default → Primary*
 */
export interface MediaWithTextSliceDefaultPrimary {
  /**
   * Image field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Overline field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_with_text.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_with_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_with_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media_with_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Reversed field in *MediaWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media_with_text.default.primary.reversed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reversed: prismic.BooleanField;
}

/**
 * Default variation for MediaWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MediaWithText*
 */
type MediaWithTextSliceVariation = MediaWithTextSliceDefault;

/**
 * MediaWithText Shared Slice
 *
 * - **API ID**: `media_with_text`
 * - **Description**: MediaWithText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaWithTextSlice = prismic.SharedSlice<
  "media_with_text",
  MediaWithTextSliceVariation
>;

/**
 * Primary content in *Parallax → Default → Primary*
 */
export interface ParallaxSliceDefaultPrimary {
  /**
   * Background Media field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.background_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Overline field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Desktop Ratio field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.desktop_ratio
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  desktop_ratio: prismic.NumberField;

  /**
   * Mobile Ratio field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.mobile_ratio
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  mobile_ratio: prismic.NumberField;

  /**
   * Anchor ID field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Title Tag field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h2
   * - **API ID Path**: parallax.default.primary.title_tag
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  title_tag: prismic.SelectField<"h2" | "h1", "filled">;

  /**
   * Content Vertical Spacing field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.content_vertical_spacing
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  content_vertical_spacing: prismic.NumberField;

  /**
   * Mobile Content Vertical Spacing field in *Parallax → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax.default.primary.mobile_content_vertical_spacing
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  mobile_content_vertical_spacing: prismic.NumberField;
}

/**
 * Default variation for Parallax Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ParallaxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParallaxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Parallax*
 */
type ParallaxSliceVariation = ParallaxSliceDefault;

/**
 * Parallax Shared Slice
 *
 * - **API ID**: `parallax`
 * - **Description**: Parallax
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ParallaxSlice = prismic.SharedSlice<
  "parallax",
  ParallaxSliceVariation
>;

/**
 * Primary content in *Quotes → Default → Primary*
 */
export interface QuotesSliceDefaultPrimary {
  /**
   * Text field in *Quotes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Subtitle field in *Quotes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quotes.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Quotes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuotesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuotesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quotes*
 */
type QuotesSliceVariation = QuotesSliceDefault;

/**
 * Quotes Shared Slice
 *
 * - **API ID**: `quotes`
 * - **Description**: Quotes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuotesSlice = prismic.SharedSlice<"quotes", QuotesSliceVariation>;

/**
 * Primary content in *Seperator → Default → Primary*
 */
export interface SeperatorSliceDefaultPrimary {
  /**
   * Top Space field in *Seperator → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: seperator.default.primary.top_space
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  top_space: prismic.NumberField;

  /**
   * Bottom Space field in *Seperator → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: seperator.default.primary.bottom_space
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  bottom_space: prismic.NumberField;

  /**
   * Show Line field in *Seperator → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: seperator.default.primary.show_line
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_line: prismic.BooleanField;

  /**
   * Anchor Id field in *Seperator → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seperator.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;
}

/**
 * Default variation for Seperator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeperatorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeperatorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Seperator*
 */
type SeperatorSliceVariation = SeperatorSliceDefault;

/**
 * Seperator Shared Slice
 *
 * - **API ID**: `seperator`
 * - **Description**: Seperator
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeperatorSlice = prismic.SharedSlice<
  "seperator",
  SeperatorSliceVariation
>;

/**
 * Primary content in *SplitPageHero → Default → Primary*
 */
export interface SplitPageHeroSliceDefaultPrimary {
  /**
   * Overline field in *SplitPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_page_hero.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *SplitPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_page_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *SplitPageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: split_page_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SplitPageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SplitPageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitPageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SplitPageHero*
 */
type SplitPageHeroSliceVariation = SplitPageHeroSliceDefault;

/**
 * SplitPageHero Shared Slice
 *
 * - **API ID**: `split_page_hero`
 * - **Description**: SplitPageHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SplitPageHeroSlice = prismic.SharedSlice<
  "split_page_hero",
  SplitPageHeroSliceVariation
>;

/**
 * Primary content in *StartHero → Default → Primary*
 */
export interface StartHeroSliceDefaultPrimary {
  /**
   * Background Media field in *StartHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: start_hero.default.primary.background_media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Overline field in *StartHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: start_hero.default.primary.overline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overline: prismic.KeyTextField;

  /**
   * Title field in *StartHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: start_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *StartHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: start_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *StartHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: start_hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for StartHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StartHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StartHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StartHero*
 */
type StartHeroSliceVariation = StartHeroSliceDefault;

/**
 * StartHero Shared Slice
 *
 * - **API ID**: `start_hero`
 * - **Description**: StartHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StartHeroSlice = prismic.SharedSlice<
  "start_hero",
  StartHeroSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Members*
 */
export interface TeamSliceDefaultPrimaryMembersItem {
  /**
   * Name field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Role field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Email field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  members: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryMembersItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *TitleTextList → Default → Primary → Items*
 */
export interface TitleTextListSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *TitleTextList → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_text_list.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TitleTextList → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_text_list.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *TitleTextList → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_text_list.default.primary.items[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *TitleTextList → Default → Primary*
 */
export interface TitleTextListSliceDefaultPrimary {
  /**
   * Items field in *TitleTextList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: title_text_list.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<TitleTextListSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for TitleTextList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleTextListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleTextListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleTextList*
 */
type TitleTextListSliceVariation = TitleTextListSliceDefault;

/**
 * TitleTextList Shared Slice
 *
 * - **API ID**: `title_text_list`
 * - **Description**: TitleTextList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TitleTextListSlice = prismic.SharedSlice<
  "title_text_list",
  TitleTextListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GeneralSettingsDocument,
      GeneralSettingsDocumentData,
      GeneralSettingsDocumentDataSocialMediaLinksItem,
      GeneralSettingsDocumentDataMenuItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionGroupSlice,
      AccordionGroupSliceDefaultPrimaryItemsItem,
      AccordionGroupSliceDefaultPrimary,
      AccordionGroupSliceVariation,
      AccordionGroupSliceDefault,
      AnimatedNumbersSlice,
      AnimatedNumbersSliceDefaultPrimaryNumbersItem,
      AnimatedNumbersSliceDefaultPrimary,
      AnimatedNumbersSliceAnimatedNumbersSplitRowPrimaryNumbersItem,
      AnimatedNumbersSliceAnimatedNumbersSplitRowPrimary,
      AnimatedNumbersSliceVariation,
      AnimatedNumbersSliceDefault,
      AnimatedNumbersSliceAnimatedNumbersSplitRow,
      FullMediaSlice,
      FullMediaSliceDefaultPrimary,
      FullMediaSliceVariation,
      FullMediaSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimaryItemsItem,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      LargeTextSlice,
      LargeTextSliceDefaultPrimary,
      LargeTextSliceVariation,
      LargeTextSliceDefault,
      LogosSlice,
      LogosSliceDefaultItem,
      LogosSliceVariation,
      LogosSliceDefault,
      MediaWithTextSlice,
      MediaWithTextSliceDefaultPrimary,
      MediaWithTextSliceVariation,
      MediaWithTextSliceDefault,
      ParallaxSlice,
      ParallaxSliceDefaultPrimary,
      ParallaxSliceVariation,
      ParallaxSliceDefault,
      QuotesSlice,
      QuotesSliceDefaultPrimary,
      QuotesSliceVariation,
      QuotesSliceDefault,
      SeperatorSlice,
      SeperatorSliceDefaultPrimary,
      SeperatorSliceVariation,
      SeperatorSliceDefault,
      SplitPageHeroSlice,
      SplitPageHeroSliceDefaultPrimary,
      SplitPageHeroSliceVariation,
      SplitPageHeroSliceDefault,
      StartHeroSlice,
      StartHeroSliceDefaultPrimary,
      StartHeroSliceVariation,
      StartHeroSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryMembersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TitleTextListSlice,
      TitleTextListSliceDefaultPrimaryItemsItem,
      TitleTextListSliceDefaultPrimary,
      TitleTextListSliceVariation,
      TitleTextListSliceDefault,
    };
  }
}
