// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  accordion_group: defineAsyncComponent(
    () => import("./AccordionGroup/index.vue"),
  ),
  animated_numbers: defineAsyncComponent(
    () => import("./AnimatedNumbers/index.vue"),
  ),
  full_media: defineAsyncComponent(() => import("./FullMedia/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  image_cards: defineAsyncComponent(() => import("./ImageCards/index.vue")),
  large_text: defineAsyncComponent(() => import("./LargeText/index.vue")),
  logos: defineAsyncComponent(() => import("./Logos/index.vue")),
  media_with_text: defineAsyncComponent(
    () => import("./MediaWithText/index.vue"),
  ),
  parallax: defineAsyncComponent(() => import("./Parallax/index.vue")),
  quotes: defineAsyncComponent(() => import("./Quotes/index.vue")),
  seperator: defineAsyncComponent(() => import("./Seperator/index.vue")),
  split_page_hero: defineAsyncComponent(
    () => import("./SplitPageHero/index.vue"),
  ),
  start_hero: defineAsyncComponent(() => import("./StartHero/index.vue")),
  team: defineAsyncComponent(() => import("./Team/index.vue")),
  title_text_list: defineAsyncComponent(
    () => import("./TitleTextList/index.vue"),
  ),
});
